import React from "react";

function Admin() {
  return <div>Admin</div>;
}

export default Admin;

/* 
    THIS NEEDED TO IMPLEMENT
    THE API CORRELATION
    - ADD THE SKU
    - CHANGE DYNAMICALLY THE TRUCK CAPACITY
    - MAKE USE OF NEWLT ADDED TRUCK THRESHOLD
    - MAKE A MORE UNDERSTANDABLE RECORDS THAT CORRELATE TO OTHERS

    THIS IS THE PICKING OF PRODUCT INSIDE THE WAREHOUSE TO BE READY IN THE TRUCK

    THE USER MUST GET THE ORDER PAPER TO INPUT THE NECESSARY PRODUCT OF THE CLIENT


*/
